---
- name: tomacat9 install
  hosts: appserver
  become: yes
  tasks:
    - name: update cache the ubuntu
      ansible.builtin.apt:
         update_cache: yes
      when: ansible_facts['os_family'] == "Debian"
    - name: java install
      ansible.builtin.package:
        name: "{{ java_package }}"
        state: present
      when: ansible_facts['os_family'] == "Debian"