---
- name: reusing playbook
  hosts: all
  become: yes
  tasks:
    - name: install tasks
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - git 
        - tree
